name = "JuliaPrediction"
uuid = "87c9edae-d709-49c4-a741-73fc75d44d62"
authors = ["chaussr"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
